/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ADVAN
 */
public class Mie_Gacoan extends javax.swing.JFrame {

    /**
     * Creates new form Mie_Gacoan
     */
    public Mie_Gacoan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Foto2 = new javax.swing.JLabel();
        Cbmiegacoan = new javax.swing.JCheckBox();
        Cbesgobak = new javax.swing.JCheckBox();
        MieGacoan = new javax.swing.JSpinner();
        esgobak = new javax.swing.JSpinner();
        BtnBeli = new javax.swing.JButton();
        BtnHapus = new javax.swing.JButton();
        BtnKeluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaStruk = new javax.swing.JTextArea();
        TextFieldBayar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Cbhotmilo = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        spinmilo = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cbpangsit = new javax.swing.JCheckBox();
        spinpangsit = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cbudangkeju = new javax.swing.JCheckBox();
        spinudangkeju = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cbesmilo = new javax.swing.JCheckBox();
        spinicemilo = new javax.swing.JSpinner();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        cbSiomay = new javax.swing.JCheckBox();
        SpinSiomay = new javax.swing.JSpinner();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        cbLumpia = new javax.swing.JCheckBox();
        spinLumpia = new javax.swing.JSpinner();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        cbUrambutan = new javax.swing.JCheckBox();
        spinUrambutan = new javax.swing.JSpinner();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));

        jPanel1.setBackground(new java.awt.Color(0, 255, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Foto2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADVAN\\Downloads\\es gobak sodor.jpg")); // NOI18N
        jPanel1.add(Foto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 120, 130));

        Cbmiegacoan.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Cbmiegacoan.setText("Pesan");
        jPanel1.add(Cbmiegacoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        Cbesgobak.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Cbesgobak.setText("Pesan");
        jPanel1.add(Cbesgobak, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        MieGacoan.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jPanel1.add(MieGacoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 170, -1));

        esgobak.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jPanel1.add(esgobak, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 169, -1));

        BtnBeli.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        BtnBeli.setText("Beli");
        BtnBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBeliActionPerformed(evt);
            }
        });
        jPanel1.add(BtnBeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 680, -1, -1));

        BtnHapus.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        BtnHapus.setText("Hapus");
        BtnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHapusActionPerformed(evt);
            }
        });
        jPanel1.add(BtnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 680, -1, -1));

        BtnKeluar.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        BtnKeluar.setText("Keluar");
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 680, -1, -1));

        TextAreaStruk.setColumns(20);
        TextAreaStruk.setRows(5);
        jScrollPane1.setViewportView(TextAreaStruk);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 640, 490, 370));

        TextFieldBayar.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jPanel1.add(TextFieldBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 670, 230, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Mie Gacoan");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Harga: Rp.11.000");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("ES GOBAK SODOR");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("Harga: Rp.13.500");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Tax : 11%");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 740, -1, -1));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, -1, 129));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setText("Hot Milo");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setText("Harga: Rp.12.000");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, -1, -1));

        Cbhotmilo.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Cbhotmilo.setText("Pesan");
        jPanel1.add(Cbhotmilo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel9.setText("Detail Pesanan");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 790, -1, -1));

        spinmilo.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jPanel1.add(spinmilo, new org.netbeans.lib.awtextra.AbsoluteConstraints(673, 90, 150, -1));
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, -1, 116));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel11.setText("Pangsit Goreng");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel12.setText("Harga: Rp.16.000");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, -1, -1));

        cbpangsit.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        cbpangsit.setText("Pesan");
        jPanel1.add(cbpangsit, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, -1, -1));

        spinpangsit.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jPanel1.add(spinpangsit, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 220, 150, -1));
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, -1, 120));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel14.setText("Udang Keju");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, -1, -1));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel15.setText("Harga: Rp.15.500");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 40, -1, -1));

        cbudangkeju.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        cbudangkeju.setText("Pesan");
        jPanel1.add(cbudangkeju, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 70, -1, -1));

        spinudangkeju.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jPanel1.add(spinudangkeju, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 80, 160, -1));
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 130, -1, 120));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel17.setText("Ice Milo");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 130, -1, -1));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel18.setText("Harga: Rp.12.000");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 160, -1, -1));

        cbesmilo.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        cbesmilo.setText("Pesan");
        jPanel1.add(cbesmilo, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 210, -1, -1));

        spinicemilo.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jPanel1.add(spinicemilo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 210, 160, -1));
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 450, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADVAN\\Downloads\\siomay ayam.jpg")); // NOI18N
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 120, -1));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel21.setText("Siomay Ayam");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel22.setText("Harga: Rp.15.000");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, -1, -1));

        cbSiomay.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        cbSiomay.setText("Pesan");
        jPanel1.add(cbSiomay, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, -1, -1));

        SpinSiomay.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jPanel1.add(SpinSiomay, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 160, -1));
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, -1, -1));

        jLabel25.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADVAN\\Downloads\\udang keju.jpg")); // NOI18N
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, 150, 100));

        jLabel26.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADVAN\\Downloads\\ice milo.jpg")); // NOI18N
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 130, 130, 120));

        jLabel27.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADVAN\\Downloads\\miegacoan.jpg")); // NOI18N
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 110));

        jLabel28.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADVAN\\Downloads\\hot milo.jpg")); // NOI18N
        jLabel28.setText("jLabel28");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 120, 120));

        jLabel29.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADVAN\\Downloads\\pangsit goreng.jpg")); // NOI18N
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 140, 130));

        jLabel30.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADVAN\\Downloads\\lumpia udang.jpg")); // NOI18N
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 150, 150));

        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel31.setText("Lumpia Udang");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, -1, -1));

        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel32.setText("Harga: Rp.13.500");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, -1, -1));

        cbLumpia.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        cbLumpia.setText("Pesan");
        jPanel1.add(cbLumpia, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, -1, -1));

        spinLumpia.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jPanel1.add(spinLumpia, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 390, 150, 30));

        jLabel33.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADVAN\\Downloads\\udang rambutan.jpg")); // NOI18N
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 280, -1, -1));

        jLabel34.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel34.setText("Udang Rambutan");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 290, -1, -1));

        jLabel35.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel35.setText("Harga: Rp.13.500");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 320, -1, -1));

        cbUrambutan.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        cbUrambutan.setText("Pesan");
        jPanel1.add(cbUrambutan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 370, -1, -1));

        spinUrambutan.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jPanel1.add(spinUrambutan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 370, 140, -1));

        jLabel36.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADVAN\\Downloads\\gacoan.png")); // NOI18N
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 780, -1, -1));
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 730, -1, -1));

        jLabel38.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel38.setText("Jumlah Uang Rp");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 670, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBeliActionPerformed
        // TODO add your handling code here:
        int total = 0;
        String struk = "===== STRUK PEMESANAN =====\n";

        if (Cbmiegacoan.isSelected()) {
            int qty = (int) MieGacoan.getValue();
            int harga = 11000;
            int subtotal = qty * harga;
            total += subtotal;
            struk += "Mie Gacoan x" + qty + " = Rp " + subtotal + "\n";
        }

        if (Cbesgobak.isSelected()) {
            int qty = (int) esgobak.getValue();
            int harga = 13500;
            int subtotal = qty * harga;
            total += subtotal;
            struk += "Es Gobak Sodor x" + qty + " = Rp " + subtotal + "\n";
        }
        if (Cbhotmilo.isSelected()) {
            int qty = (int) spinmilo.getValue();
            int harga = 12000;
            int subtotal = qty * harga;
            total += subtotal;
            struk += "Hot Milo" + qty + " = Rp " + subtotal + "\n";
        }
        if (cbpangsit.isSelected()) {
            int qty = (int) spinpangsit.getValue();
            int harga = 16000;
            int subtotal = qty * harga;
            total += subtotal;
            struk += "Pangsit Goreng" + qty + " = Rp " + subtotal + "\n";
        }
        if (cbesmilo.isSelected()) {
            int qty = (int) spinicemilo.getValue();
            int harga = 12000;
            int subtotal = qty * harga;
            total += subtotal;
            struk += "Ice Milo" + qty + " = Rp " + subtotal + "\n";
        }
        if (cbudangkeju.isSelected()) {
            int qty = (int) spinudangkeju.getValue();
            int harga = 15500;
            int subtotal = qty * harga;
            total += subtotal;
            struk += "Udang Keju" + qty + " = Rp " + subtotal + "\n";
        }
        if (cbSiomay.isSelected()) {
            int qty = (int) SpinSiomay.getValue();
            int harga = 15000;
            int subtotal = qty * harga;
            total += subtotal;
            struk += "Siomay Ayam" + qty + " = Rp " + subtotal + "\n";
        }
        if (cbLumpia.isSelected()) {
            int qty = (int) spinLumpia.getValue();
            int harga = 13500;
            int subtotal = qty * harga;
            total += subtotal;
            struk += "Lumpia Udang" + qty + " = Rp " + subtotal + "\n";
        }
        if (cbUrambutan.isSelected()) {
            int qty = (int) spinUrambutan.getValue();
            int harga = 13500;
            int subtotal = qty * harga;
            total += subtotal;
            struk += "Udang Rambutan" + qty + " = Rp " + subtotal + "\n";
        }
        
        struk += "----------------------------\n";
        double ppn = total * 0.11;
        int totalAkhir = total + (int) ppn;

        struk += String.format("PPN 11%%         : Rp %d\n", (int) ppn);
        struk += String.format("TOTAL BAYAR     : Rp %d\n", totalAkhir);
        
        // Ambil input dari TextFieldBayar
        int uangBayar = Integer.parseInt(TextFieldBayar.getText());

        // Hitung kembalian
        int kembalian = uangBayar - totalAkhir;

        struk += String.format("UANG DIBAYARKAN : Rp %d\n", uangBayar);
        struk += String.format("KEMBALIAN       : Rp %d\n", kembalian);

        TextAreaStruk.setText(struk);
    }//GEN-LAST:event_BtnBeliActionPerformed

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHapusActionPerformed
        // TODO add your handling code here:
        Cbmiegacoan.setSelected(false);
        Cbesgobak.setSelected(false);
        Cbhotmilo.setSelected(false);
        cbpangsit.setSelected(false);
        cbudangkeju.setSelected(false);
        cbesmilo.setSelected(false);

        MieGacoan.setValue(0);
        esgobak.setValue(0);
        spinmilo.setValue(0);
        spinpangsit.setValue(0);
        spinudangkeju.setValue(0);
        spinicemilo.setValue(0);
        
        TextAreaStruk.setText("");
    }//GEN-LAST:event_BtnHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mie_Gacoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mie_Gacoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mie_Gacoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mie_Gacoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mie_Gacoan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBeli;
    private javax.swing.JButton BtnHapus;
    private javax.swing.JButton BtnKeluar;
    private javax.swing.JCheckBox Cbesgobak;
    private javax.swing.JCheckBox Cbhotmilo;
    private javax.swing.JCheckBox Cbmiegacoan;
    private javax.swing.JLabel Foto2;
    private javax.swing.JSpinner MieGacoan;
    private javax.swing.JSpinner SpinSiomay;
    private javax.swing.JTextArea TextAreaStruk;
    private javax.swing.JTextField TextFieldBayar;
    private javax.swing.JCheckBox cbLumpia;
    private javax.swing.JCheckBox cbSiomay;
    private javax.swing.JCheckBox cbUrambutan;
    private javax.swing.JCheckBox cbesmilo;
    private javax.swing.JCheckBox cbpangsit;
    private javax.swing.JCheckBox cbudangkeju;
    private javax.swing.JSpinner esgobak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spinLumpia;
    private javax.swing.JSpinner spinUrambutan;
    private javax.swing.JSpinner spinicemilo;
    private javax.swing.JSpinner spinmilo;
    private javax.swing.JSpinner spinpangsit;
    private javax.swing.JSpinner spinudangkeju;
    // End of variables declaration//GEN-END:variables
}
