/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tiket_Pesawat;

/**
 *
 * @author ADVAN
 */
public class Menu_Utama extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Utama
     */
    public Menu_Utama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelHeader = new javax.swing.JPanel();
        lblJudul = new javax.swing.JLabel();
        panelMenu = new javax.swing.JPanel();
        btnTiket = new javax.swing.JButton();
        btnJadwal = new javax.swing.JButton();
        btnMaskapai = new javax.swing.JButton();
        btnRute = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        panelFooter = new javax.swing.JPanel();
        lblCopyright = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelHeader.setBackground(new java.awt.Color(0, 123, 255));
        panelHeader.setLayout(new java.awt.GridLayout(1, 0));

        lblJudul.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        lblJudul.setForeground(new java.awt.Color(255, 255, 255));
        lblJudul.setText("SKYTIX - Pemesanan Tiket Pesawat");
        panelHeader.add(lblJudul);

        getContentPane().add(panelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -3, 1270, 110));

        panelMenu.setBackground(new java.awt.Color(51, 255, 51));
        panelMenu.setLayout(new javax.swing.BoxLayout(panelMenu, javax.swing.BoxLayout.LINE_AXIS));

        btnTiket.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnTiket.setText("Kelola Tiket");
        btnTiket.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        btnTiket.setMargin(new java.awt.Insets(2, 20, 2, 20));
        btnTiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTiketActionPerformed(evt);
            }
        });
        panelMenu.add(btnTiket);

        btnJadwal.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnJadwal.setText("Kelola Jadwal");
        btnJadwal.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        btnJadwal.setMargin(new java.awt.Insets(2, 20, 2, 20));
        panelMenu.add(btnJadwal);

        btnMaskapai.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnMaskapai.setText("Kelola Maskapai");
        btnMaskapai.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        btnMaskapai.setMargin(new java.awt.Insets(2, 20, 2, 20));
        btnMaskapai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaskapaiActionPerformed(evt);
            }
        });
        panelMenu.add(btnMaskapai);

        btnRute.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnRute.setText("Kelola Rute");
        btnRute.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        btnRute.setMargin(new java.awt.Insets(2, 20, 2, 20));
        panelMenu.add(btnRute);

        btnLogout.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        btnLogout.setMargin(new java.awt.Insets(2, 20, 2, 20));
        panelMenu.add(btnLogout);

        getContentPane().add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 108, 1270, 360));

        panelFooter.setBackground(new java.awt.Color(255, 255, 102));
        panelFooter.setLayout(new java.awt.GridBagLayout());

        lblCopyright.setText("\"© 2025 SkyTix Inc. All rights reserved.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(44, 912, 36, 73);
        panelFooter.add(lblCopyright, gridBagConstraints);

        getContentPane().add(panelFooter, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 1270, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMaskapaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaskapaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMaskapaiActionPerformed

    private void btnTiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTiketActionPerformed
        new kelolaTiket().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnTiketActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJadwal;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMaskapai;
    private javax.swing.JButton btnRute;
    private javax.swing.JButton btnTiket;
    private javax.swing.JLabel lblCopyright;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JPanel panelFooter;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelMenu;
    // End of variables declaration//GEN-END:variables
}
