/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package latihan1;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author ADVAN
 */
public class Perhitungan extends javax.swing.JFrame {

    /**
     * Creates new form Perhitungan
     */
    public Perhitungan() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("Kalkulator Sederhana");

        // Skalakan gambar dan atur ke jLabel4
        ImageIcon icon = new ImageIcon(getClass().getResource("/latihan1/1369269.png"));
        Image img = icon.getImage().getScaledInstance(700, 500, Image.SCALE_SMOOTH); // sesuaikan ukuran
        jLabel4.setIcon(new ImageIcon(img));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_angka1 = new javax.swing.JTextField();
        txt_angka2 = new javax.swing.JTextField();
        txt_hasil = new javax.swing.JTextField();
        btn_tambah = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_keluar = new javax.swing.JButton();
        btn_kali = new javax.swing.JButton();
        btn_kurang = new javax.swing.JButton();
        btn_bagi = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Angka Pertama");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 75, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Angka Kedua");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Hasil");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 310, -1, -1));

        txt_angka1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jPanel1.add(txt_angka1, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 72, 417, -1));

        txt_angka2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jPanel1.add(txt_angka2, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 127, 417, -1));

        txt_hasil.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jPanel1.add(txt_hasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 307, 417, -1));

        btn_tambah.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btn_tambah.setText("+");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });
        jPanel1.add(btn_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 180, 82, 67));

        btn_hapus.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btn_hapus.setText("HAPUS");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        jPanel1.add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 426, -1, -1));

        btn_keluar.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        btn_keluar.setText("KELUAR");
        btn_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keluarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 426, -1, -1));

        btn_kali.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btn_kali.setText("X");
        btn_kali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kaliActionPerformed(evt);
            }
        });
        jPanel1.add(btn_kali, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 180, 76, 67));

        btn_kurang.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btn_kurang.setText("-");
        btn_kurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kurangActionPerformed(evt);
            }
        });
        jPanel1.add(btn_kurang, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 180, 71, 67));

        btn_bagi.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btn_bagi.setText("/");
        btn_bagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bagiActionPerformed(evt);
            }
        });
        jPanel1.add(btn_bagi, new org.netbeans.lib.awtextra.AbsoluteConstraints(594, 180, 72, 67));

        jLabel4.setMinimumSize(new java.awt.Dimension(1000, 1000));
        jLabel4.setPreferredSize(new java.awt.Dimension(1000, 1000));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jLabel4, org.jdesktop.beansbinding.ELProperty.create("${minimumSize}"), jLabel4, org.jdesktop.beansbinding.BeanProperty.create("icon"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jLabel4, org.jdesktop.beansbinding.ELProperty.create("${displayedMnemonic}"), jLabel4, org.jdesktop.beansbinding.BeanProperty.create("disabledIcon"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jLabel4, org.jdesktop.beansbinding.ELProperty.create("${displayedMnemonic}"), jLabel4, org.jdesktop.beansbinding.BeanProperty.create("displayedMnemonicIndex"));
        bindingGroup.addBinding(binding);

        jLabel4.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel4PropertyChange(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_keluarActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        txt_angka1.setText("");
        txt_angka2.setText("");
        txt_hasil.setText("");
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        // TODO add your handling code here:
        try {
        int angka1 = Integer.parseInt(txt_angka1.getText());
        int angka2 = Integer.parseInt(txt_angka2.getText());
        int hasil = angka1 + angka2;
        txt_hasil.setText(String.valueOf(hasil));
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Masukkan angka yang valid!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_kaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kaliActionPerformed
        // TODO add your handling code here:
        try {
        int angka1 = Integer.parseInt(txt_angka1.getText());
        int angka2 = Integer.parseInt(txt_angka2.getText());
        int hasil = angka1 * angka2;
        txt_hasil.setText(String.valueOf(hasil));
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Masukkan angka yang valid!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btn_kaliActionPerformed

    private void btn_kurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kurangActionPerformed
        // TODO add your handling code here:
        try {
        int angka1 = Integer.parseInt(txt_angka1.getText());
        int angka2 = Integer.parseInt(txt_angka2.getText());
        int hasil = angka1 - angka2;
        txt_hasil.setText(String.valueOf(hasil));
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Masukkan angka yang valid!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btn_kurangActionPerformed

    private void btn_bagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bagiActionPerformed
        // TODO add your handling code here:
       try {
    double angka1 = Double.parseDouble(txt_angka1.getText());
    double angka2 = Double.parseDouble(txt_angka2.getText());

    if (angka2 == 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Tidak bisa membagi dengan nol!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    } else {
        double hasil = angka1 / angka2;
        txt_hasil.setText(String.valueOf(hasil));
    }
} catch (NumberFormatException e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Masukkan angka yang valid!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
}

    }//GEN-LAST:event_btn_bagiActionPerformed

    private void jLabel4PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel4PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4PropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Perhitungan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Perhitungan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Perhitungan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Perhitungan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Perhitungan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bagi;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_kali;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_kurang;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_angka1;
    private javax.swing.JTextField txt_angka2;
    private javax.swing.JTextField txt_hasil;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}