/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ADVAN
 */
import java.text.SimpleDateFormat;
public class Pemesanan extends javax.swing.JFrame {

    /**
     * Creates new form Pemesanan
     */
    public Pemesanan() {
                  initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Ekonomi = new javax.swing.JRadioButton();
        Bisnis = new javax.swing.JRadioButton();
        First_Class = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        btnPesan = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        spinTiket = new javax.swing.JSpinner();
        cmbTujuan = new javax.swing.JComboBox<>();
        txtNama = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnKeluar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cmbAsal = new javax.swing.JComboBox<>();
        date = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 255, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("Nama Penumpang");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Tujuan");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("Tanggal Berangkat");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setText("Kelas Penerbangan :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setText(":");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        buttonGroup1.add(Ekonomi);
        Ekonomi.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Ekonomi.setText("Ekonomi");
        jPanel1.add(Ekonomi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        buttonGroup1.add(Bisnis);
        Bisnis.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Bisnis.setText("Bisnis");
        jPanel1.add(Bisnis, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, -1));

        buttonGroup1.add(First_Class);
        First_Class.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        First_Class.setText("First Class");
        jPanel1.add(First_Class, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel6.setText("Jumlah Tiket :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        btnPesan.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnPesan.setText("PESAN");
        btnPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesanActionPerformed(evt);
            }
        });
        jPanel1.add(btnPesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        btnReset.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel1.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 490, 200));

        spinTiket.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jPanel1.add(spinTiket, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 90, -1));

        cmbTujuan.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        cmbTujuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jakarta", "Surabaya", "Bali", "Medan", " " }));
        jPanel1.add(cmbTujuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 170, -1));

        txtNama.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jPanel1.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 16, 170, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel7.setText(":");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel8.setText(":");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        btnKeluar.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnKeluar.setText("KELUAR");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        jPanel1.add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel9.setText("Asal");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel10.setText(":");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

        cmbAsal.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        cmbAsal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Medan", "Surabaya", "Bali", "Jakarta", " " }));
        jPanel1.add(cmbAsal, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 64, 170, -1));
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 170, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesanActionPerformed
    String nama = txtNama.getText();
    String tujuan = (String) cmbTujuan.getSelectedItem();
    SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
    String tanggal = (date.getDate() != null) ? sdf.format(date.getDate()) : "-";


    
    int jumlahTiket = (int) spinTiket.getValue();
    
    String kelas = "";
    int hargaPerTiket = 0;
    
    if (Ekonomi.isSelected()) {
        kelas = "Ekonomi";
        hargaPerTiket = 500000;
    } else if (Bisnis.isSelected()) {
        kelas = "Bisnis";
        hargaPerTiket = 1000000;
    } else if (First_Class.isSelected()) {
        kelas = "First Class";
        hargaPerTiket = 2000000;
    }

    int totalHarga = jumlahTiket * hargaPerTiket;

    String struk = 
        "======= STRUK PEMESANAN =======\n" +
        "Nama Penumpang : " + nama + "\n" +
        "Tujuan         : " + tujuan + "\n" +
        "Tanggal        : " + tanggal + "\n" +
        "Kelas          : " + kelas + "\n" +
        "Jumlah Tiket   : " + jumlahTiket + "\n" +
        "Total Harga    : Rp " + totalHarga + "\n" +
        "===============================\n";

    jTextArea1.setText(struk);
    }//GEN-LAST:event_btnPesanActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtNama.setText("");
        cmbTujuan.setSelectedIndex(0); // atau -1 untuk kosong
        date.setDate(null);
        buttonGroup1.clearSelection();
        spinTiket.setValue(0);
        jTextArea1.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pemesanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Bisnis;
    private javax.swing.JRadioButton Ekonomi;
    private javax.swing.JRadioButton First_Class;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnPesan;
    private javax.swing.JButton btnReset;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbAsal;
    private javax.swing.JComboBox<String> cmbTujuan;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JSpinner spinTiket;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables
}
